services:
  db:
    image: mysql:latest
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: cloudtech

  backend:
    image: api-image
    container_name: api-container
    depends_on:
      - db
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=cloudtech
      - DB_SERVERNAME=db-container
    ports:
      - "8080:8080"

  frontend:
    image: front-image
    container_name: front-container
    depends_on:
      - db
    ports:
      - "8081:80"
